# TensorFlow

### TensorFlow Installation Guide

## Follow Official Installation Instructions
Before proceeding, check the official TensorFlow installation guide for your operating system:
🔗 [TensorFlow Installation Guide](https://www.tensorflow.org/install)

## Installing TensorFlow on MacOS

### 1️⃣ Install TensorFlow via pip
TensorFlow does not officially support GPUs on MacOS, so it will run on **CPU only**. To install TensorFlow, run:

```bash
!python3 -m pip install tensorflow
```

### 2️⃣ Verify the Installation
Once installed, verify it by running:

```bash
!python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
```

### 3️⃣ (Optional) Optimizing for Apple Silicon (M1/M2/M3)
If you're using an **Apple Silicon Mac**, install the optimized version of TensorFlow:

```bash
!python3 -m pip install tensorflow-macos tensorflow-metal
```

### 4️⃣ Upgrade pip (if needed)
If you run into errors, try upgrading pip before installing TensorFlow:

```bash
!pip install --upgrade pip
!pip install tensorflow-macos
```

## ✅ Troubleshooting
- If you face **compatibility issues**, check the official documentation for **specific MacOS versions and Python compatibility**.
- For **Windows/Linux users**, follow the [official guide](https://www.tensorflow.org/install) to install TensorFlow properly.


In [4]:
# There is currently no official GPU support for MacOS.
!python3 -m pip install tensorflow
# Verify the installation:
!python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

2025-02-26 21:53:29.184776: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf.Tensor(825.8768, shape=(), dtype=float32)


In [7]:
import tensorflow as tf

2025-02-26 22:21:36.724928: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
# Disable eager execution (required for InteractiveSession)
tf.compat.v1.disable_eager_execution()

# Create an Interactive Session
sess = tf.compat.v1.InteractiveSession()

print("Session created successfully!")


Session created successfully!


## TensorFlow Basics
We will go over how to create a simple constant with TensorFlow, by passing in a very simple object `'Hello World!'`

In [1]:
import tensorflow as tf

2025-03-04 13:40:44.358885: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [5]:
tf.constant('Hello World!')

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello World!'>

In [8]:
hello = tf.constant('Hello World!')

In [10]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [12]:
x = tf.constant(100)

In [14]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=100>

**Create a TensorFlow Session**
In TensorFlow 2.x, a session (`tf.Session()`) is not required to execute a tensor. Instead, eager execution is enabled by default, allowing tensors to be evaluated instantly.

### For TF 1.x Compatibility
However if you need to run an operation Using a Session
If you're working with TensorFlow 1.x style code in TensorFlow 2.x, you can disable eager execution and use a session:

In [4]:
import tensorflow as tf

 # Disable eager mode
tf.compat.v1.disable_eager_execution() 

# Create a constant tensor object
hello = tf.constant('Hello World!')

# Create and run a session
with tf.compat.v1.Session() as sess:
    print(sess.run(hello).decode("utf-8"))

# print(tf.get_static_value(hello).decode("utf-8"))

Hello World!


### Running the "Hello World" Tensor in TensorFlow 2.x

In [26]:
hello = tf.constant(b'Hello World!')

print(hello)

# Convert to NumPy bytes before decoding
# print(hello.numpy().tobytes().decode("utf-8"))

Tensor("Const_10:0", shape=(), dtype=string)


In [2]:
# Operations

In [16]:
x=tf.constant(2)

In [18]:
y=tf.constant(3)

In [22]:
print('Addition: ', x+y)

Addition:  tf.Tensor(5, shape=(), dtype=int32)


In [26]:
print('Subtraction: ', x-y)

Subtraction:  tf.Tensor(-1, shape=(), dtype=int32)


In [28]:
print('Multiplication: ', x*y)

Multiplication:  tf.Tensor(6, shape=(), dtype=int32)


In [30]:
print('Division: ', x/y)

Division:  tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


In [9]:
@tf.function
def my_function(x):
    return x * 2

x_func = tf.constant(5, dtype=tf.int32)
print(my_function(x_func))


tf.Tensor(10, shape=(), dtype=int32)


In [11]:
x_func

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [7]:
x_ = tf.constant(5, dtype=tf.int32)

In [9]:
x_

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [11]:
y_=tf.constant(6,dtype=tf.int32)

In [13]:
y_

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [15]:
add=tf.add(x_,y_,)

In [17]:
add

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [35]:
x = tf.constant([1, 2], dtype=tf.int8)
>>> y = [2**7 + 1, 2**7 + 2]

In [37]:
add_ = tf.add(x,y)

In [41]:
add_

<tf.Tensor: shape=(2,), dtype=int8, numpy=array([-126, -124], dtype=int8)>

In [21]:
sub=tf.subtract(x_,y_)

In [23]:
sub

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [25]:
multiplication = tf.multiply(x_,y_)

In [27]:
multiplication

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [29]:
div=tf.divide(x_,y_)

In [31]:
div

<tf.Tensor: shape=(), dtype=float64, numpy=0.8333333333333334>

In [1]:
import tensorflow as tf

2025-03-19 20:12:46.564568: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# TensorFlow 1.x
x = tf.placeholder(tf.int32)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [13]:
# TF 2.x
x = tf.Variable(1,dtype=tf.int32)

In [19]:
y = tf.Variable(10,dtype=tf.int32)

In [15]:
x

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [21]:
y

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>